### ISSUE TITLE
Write analysis for concept exercise `rpn-calculator-output`

### ISSUE THREAD

**Issue by angelikatyborska** [exercism/elixir-analyzer#93]
Desired checks: https://github.com/exercism/elixir/blob/9774308bb6b898df6ecbde64c5c6e48c651870ae/exercises/concept/rpn-calculator-output/.meta/design.md#L25-L31

**Comment by jiegillet** [comment]
I've been looking at this one, but I got stuck somewhere.

Two of the criteria (there are more, I'm simplifying) are
* open must be before try
* write must be in the try block

For example:
```elixir
{:ok, file} = resource.open(filename)
try do
  IO.write(file, equation)
rescue 
  _ -> :error
end
```
This is OK. A naive implementation with `feature` would be
```elixir
feature "open must be before try" do
  form do
    _ignore = resource.open(filename)
    try _ignore
  end
end
```
plus 
```elixir
feature "write must be in the try block" do
  form do
    try do: IO.write(_ignore, _ignore), rescue: _ignore
  end
end
```
However, when I try this failing solution
```elixir
try do
  {:ok, file} = resource.open(filename)
  IO.write(file, equation)
rescue 
  _ -> :error
end
```
both of my features fail, because `"write must be in the try block"` only pattern matches a single line. Of course I could add one feature with an `_ignore` one top of `write`, another with one below, but that doesn't feel right.

Is there a feature of `feature` that I'm missing? 
I'm envisioning something like 
```elixir
feature "write must be in the try block" do
  form do
    try _block_includes
      IO.write(_ignore, _ignore)
   rescue
     _ignore
  end
end
```
I haven't fully grasped the code yet, so I'm not sure if it's doable. Please advise :)

**Comment by angelikatyborska** [comment]
> Of course I could add one feature with an _ignore one top of write, another with one below, but that doesn't feel right.

> Is there a feature of feature that I'm missing?

No, I'm afraid that's the "beauty" of `feature`. I often have problems with using it precisely for the same reason.

It's possible that the desired checks that we described aren't even possible with the current features of the analyzer.

The `assert_call` and `feature` macros are really nice for some checks, but in some cases I just wish we could also write an analyzer extension for an exercise by pattern matching on the AST directly. Then anything is possible! @neenjaw what do you think about this problem?

**Comment by neenjaw** [comment]
Considering feature does pattern match against the AST, I don't think what you are describing is really a feature use-case. 

I don't think this test is likely possible even with direct pattern matching, because you want to identify the presence of a node at any point inside of a do-block (which is a list of AST node), and you can't pattern match membership of an element in a list that is at any point. 

It appears that when you are asking to "pattern match directly against the AST" what you are really asking for is a way to "start at an arbitrary point in the AST, then perform a custom search for some criteria".

I think this would be an interesting addition to the tools we have now. 

Maybe would consist of some sort of "trigger" which then calls a function on some child AST

**Comment by jiegillet** [comment]
Finding a command or a list of consecutive commands in a list of children nodes shouldn't be too hard. Although like i said, I don't fully grasp the code yet. 

If that's fine with you, I'll investigate the idea and see if I can come up with something nice.

**Comment by neenjaw** [comment]
Yes, I think it would be interesting the investigate the idea but maybe if we can discuss it before committing tonnes of implementation time to it as might be able to help refine the approach to it.

**Comment by angelikatyborska** [comment]
Closed in https://github.com/exercism/elixir-analyzer/pull/120
